name: Deploy to production enviroment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: node-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ matrix.node-version }}
      - name: Setup Node@${{ matrix.node-version }} environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Build project
        run: |
          yarn
          yarn build
      - name: Upload artifacts for Node@${{ matrix.node-version }}
        uses: actions/upload-artifact@v2
        with:
          name: artifacts-node-${{ matrix.node-version }}
          path: build/
          if-no-files-found: error

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: node-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ matrix.node-version }}
      - name: Setup Node@${{ matrix.node-version }} environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Build project
        run: |
          yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/cache@v2
        id: node-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ matrix.node-version }}
      - name: Download artifacts for Node@${{ matrix.node-version }}
        uses: actions/download-artifact@v2
        with:
          name: artifacts-node-${{ matrix.node-version }}
          path: build/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
