name: Deploy to production enviroment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: node-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.15.0
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Build project
        run: |
          yarn
          yarn build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: build/*
          if-no-files-found: error

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: node-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.15.0
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Build project
        run: |
          yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/cache@v2
        id: node-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
